# -*- coding: utf-8 -*-


class Event(object):
    """
    This static class represents an enum for events.
    """
    PLOT = 0
    ENABLE_FIT_BUTTON = 1
    DISABLE_FIT_BUTTON = 2
    ENABLE_ADVANCED_BUTTON = 3
    PRINT_INFORMATION = 4
    SET_FILE_CONTENT = 5
    ENABLE_COL_DATE_FORMAT = 6
    SHOW_CANT_CONVERT_DATES = 7
    CLEAR_INPUT = 8
    NO_POPULATION = 9
    CHANGE_AVAILABILITY_OPTIONS = 10
    CHANGE_AVAILABILITY_PARAMETERS = 11
    SHOW_RUNTIME_ERROR = 12
    INVALID_DATA_RANGE = 13
    CLEAR_INFORMATION = 14
    SELECT_NEW_MODEL = 15
    SELECT_NEW_MODEL_TYPE = 16
    SELECT_WITH_PARAMETERS = 17
    INVALID_POPULATION = 18
