# -*- coding: utf-8 -*-


class Event(object):
    """
    This static class represents an enum for events.
    """
    PLOT = 0
    ENABLE_FIT_BUTTON = 1
    DISABLE_FIT_BUTTON = 2
    ENABLE_ADVANCED_BUTTON = 3
    SHOW_MODEL_PARAMETER_GROUP_BOX = 4
    PRINT_INFORMATION = 5
    SET_FILE_CONTENT = 6
    ENABLE_COL_DATE_FORMAT = 7
    SHOW_CANT_CONVERT_DATES = 8
    ENABLE_OPTIONS = 9
    CLEAR_INPUT = 10
    NO_POPULATION = 11
    DISABLE_OPTIONS = 12
    DISABLE_PARAMETERS = 13
    ENABLE_PARAMETERS = 14
    SHOW_RUNTIME_ERROR = 16
    INVALID_DATA_RANGE = 17
    CLEAR_INFORMATION = 18