# -*- coding: utf-8 -*-


class Event(object):
    """
    This static class represents an enum for events.
    """
    
    PLOT = 0
    ENABLE_FIT_BUTTON = 1
    DISABLE_FIT_BUTTON = 2
    ENABLE_ADVANCED_BUTTON = 3
    PRINT_INFORMATION = 4
    SET_FILE_CONTENT = 5
    ENABLE_COL_DATE_FORMAT = 6
    SHOW_CANT_CONVERT_DATES = 7
    CLEAR_INPUT = 8
    NO_POPULATION = 9
    ENABLE_OPTIONS_GROUP_BOX = 10
    DISABLE_OPTIONS_GROUP_BOX = 11
    CHANGE_AVAILABILITY_PARAMETERS = 12
    SHOW_RUNTIME_ERROR = 13
    INVALID_DATA_RANGE = 14
    CLEAR_INFORMATION = 15
    SELECT_NEW_MODEL = 16
    SELECT_NEW_MODEL_TYPE = 17
    SELECT_WITH_PARAMETERS = 18
    INVALID_POPULATION = 19
    UPDATE_POPULATION_FIELD = 20
    UPDATE_POPULATION_SLIDER = 21
    INVALID_DATA_PERCENTAGE = 22
    CAN_NOT_READ_FILE = 23
